server:
  port: 8021

spring:
  application:
    name: feign-hystrix-user-service
  zipkin:
    base-url: 'http://localhost:9411/'

management:
  context-path: '/admin'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://peer1:8761/eureka/,http://peer2:8762/eureka/'
  instance:
    preferIpAddress: false
    metadata-map:
      cluster: prontera
      management:
        context-path: ${management.context-path}
      health:
        path: ${management.context-path}/health
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
ribbon:
  eureka:
    enabled: true         # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。参考：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka

### 参考：https://spring.io/guides/gs/client-side-load-balancing/