spring:
  application:
    name: api-gateway
  cloud:
      loadbalancer:
        retry:
          enabled: true
  zipkin:
    base-url: 'http://localhost:9411/'

server:
  port: 8050

management:
  context-path: '/admin'

eureka:
  instance:
    hostname: gateway
    metadata-map:
      cluster: prontera
      management:
        context-path: ${management.context-path}
      health:
        path: ${management.context-path}/health
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: 'http://peer1:8761/eureka/,http://peer2:8762/eureka/'
# 下面整个树都非必须，如果不配置，将默认使用 http://GATEWAY:GATEWAY_PORT/想要访问的Eureka服务id的小写/** 路由到：http://想要访问的Eureka服务id的小写:该服务端口/**
zuul:
  routes:
    user:                                               # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /user/**                                    # 想要映射到的路径
      service-id: user-service            # Eureka中的serviceId


ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true
  ConnectTimeout: 1500
  ReadTimeout: 2000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500